import { ShopDatabase } from '../types/shop';

export const initialSeedDatabase: ShopDatabase = {
  version: '2.0.0',
  lastUpdated: new Date().toISOString(),
  settings: {
    storeName: 'TRẦN HOA COMPUTER',
    logoUrl: '',
    tagline: 'Cửa Hàng Máy Tính & Trung Tâm Kỹ Thuật Uy Tín Duy Nhất Tại Thái Nguyên',
    hotline: '0963284044',
    zalo: '84963284044',
    email: 'hotrokhachhang@tranhoacomputer.site',
    address: 'Phú Thịnh - Thái Nguyên (Cửa hàng duy nhất, không có chi nhánh trên toàn quốc)',
    workingHours: '08:00 - 21:30 (Mở cửa tất cả các ngày trong tuần & ngày lễ)',
    bankName: 'MB BANK',
    bankAccount: '0963284044',
    bankAccountName: 'TRAN HOA COMPUTER',
    announcementText: '🔥 CỬA HÀNG DUY NHẤT TẠI PHÚ THỊNH - THÁI NGUYÊN (KHÔNG CÓ CHI NHÁNH TOÀN QUỐC) · Hotline: 0963284044 · Zalo: zalo.me/84963284044 · 1 Đổi 1 Trong 30 Ngày',
    heroTitle: 'Máy Tính & Trung Tâm Kỹ Thuật Trần Hoa Computer',
    heroSubtitle: 'Địa chỉ duy nhất tại Phú Thịnh - Thái Nguyên (Không có bất cứ chi nhánh nào trên toàn quốc). Cam kết 100% linh kiện chính hãng, ship COD đồng kiểm toàn quốc.',
    heroBadge: 'CƠ SỞ DUY NHẤT TẠI PHÚ THỊNH - THÁI NGUYÊN · 100% CHÍNH HÃNG',

    // Định vị bán hàng tại một tỉnh thành (Local Province/City Focus)
    targetProvince: 'Thái Nguyên',
    provinceDeliveryNotice: 'Giao siêu tốc tại Thái Nguyên & Vận chuyển bảo hiểm bọc chống sốc 63 tỉnh thành',
    provinceExpressHours: '1 - 2 giờ',
    provinceFreeShipThreshold: 500000,

    // Bật/tắt các phương thức mua hàng & thanh toán
    enableInStorePickup: true,
    enableLocalExpress: true,
    enableCodDelivery: true,
    enableVietQR: true,
    enableInstallment: true,
    installmentHotline: '0963284044',
  },
  products: [
    {
      id: 'prod-flash-1',
      name: 'Laptop Gaming ASUS TUF Gaming A15 FA506NF - RTX 2050 4GB',
      category: 'laptop',
      brand: 'ASUS',
      price: 15490000,
      originalPrice: 19990000,
      discountPercent: 23,
      inStock: true,
      stockCount: 15,
      rating: 4.8,
      reviewCount: 142,
      imageUrl: '',
      badge: 'GIỜ VÀNG GIÁ SỐC',
      installmentZero: true,
      isFlashSale: true,
      flashSaleSold: 19,
      flashSaleTotal: 25,
      giftPromotion: 'Tặng Balo TUF Gaming + Chuột gaming có dây + Voucher 300K',
      isFeatured: true,
      specs: {
        cpu: 'AMD Ryzen 5 7535HS (6 nhân, 12 luồng, up to 4.55GHz)',
        screen: '15.6 inch FHD (1920x1080) IPS 144Hz Chống chói',
        ram: '16GB DDR5 4800MHz (2 khe)',
        storage: '512GB SSD M.2 PCIe 4.0 NVMe',
        gpu: 'NVIDIA GeForce RTX 2050 4GB GDDR6',
        weight: '2.30 kg',
        warranty: '24 Tháng chính hãng ASUS toàn quốc',
      },
      description: 'Mẫu laptop gaming quốc dân bán chạy số 1 phân khúc sinh viên và người đi làm, trang bị màn hình 144Hz mượt mà và chuẩn độ bền quân đội Mỹ MIL-STD-810H.',
    },
    {
      id: 'prod-flash-2',
      name: 'PC Gaming NEXUS E-POWER BATTLESHIP - i5 13400F / RTX 4060',
      category: 'pc_gaming',
      brand: 'NEXUS',
      price: 18990000,
      originalPrice: 22500000,
      discountPercent: 16,
      inStock: true,
      stockCount: 9,
      rating: 5.0,
      reviewCount: 97,
      imageUrl: '',
      badge: 'FLASH SALE HOT',
      installmentZero: true,
      isFlashSale: true,
      flashSaleSold: 14,
      flashSaleTotal: 20,
      giftPromotion: 'Tặng Phím cơ RGB + Chuột gaming + Lót chuột 80x30cm',
      isFeatured: true,
      specs: {
        cpu: 'Intel Core i5-13400F (10 nhân, 16 luồng, up to 4.6GHz)',
        mainboard: 'Gigabyte B760M GAMING PLUS D4',
        ram: '16GB (2x8GB) Kingston Fury Beast RGB 3200MHz',
        gpu: 'MSI GeForce RTX 4060 VENTUS 2X 8GB OC',
        storage: '512GB SSD Kingston NV2 PCIe 4.0 NVMe',
        psu: 'Cooler Master Elite V4 600W 80 Plus',
        case: 'Xigmatek Aqua M Black 3 Fan RGB',
        warranty: '36 Tháng 1 đổi 1 linh kiện',
      },
      description: 'Dàn PC gaming lắp sẵn cân tốt mọi tựa game Esport (Valorant, CS2, LMHT 240+ FPS) và game AAA ở độ phân giải Full HD / 2K mượt mà.',
    },
    {
      id: 'prod-flash-3',
      name: 'Laptop Apple MacBook Air 13 inch M3 (2024) 8CPU 8GPU 16GB',
      category: 'laptop',
      brand: 'Apple',
      price: 27490000,
      originalPrice: 29990000,
      discountPercent: 8,
      inStock: true,
      stockCount: 11,
      rating: 4.9,
      reviewCount: 88,
      imageUrl: '',
      badge: 'HÀNG CHÍNH HÃNG VNA',
      installmentZero: true,
      isFlashSale: true,
      flashSaleSold: 21,
      flashSaleTotal: 30,
      giftPromotion: 'Tặng Cổng chuyển Type-C đa năng + Túi chống sốc cao cấp',
      isFeatured: true,
      specs: {
        cpu: 'Apple M3 chip (8-core CPU, 8-core GPU, 16-core Neural Engine)',
        screen: '13.6 inch Liquid Retina (2560x1664) 500 nits True Tone',
        ram: '16GB Unified Memory',
        storage: '256GB SSD siêu tốc',
        weight: 'Chỉ 1.24 kg siêu mỏng 11.3mm',
        battery: 'Thời lượng pin ấn tượng lên đến 18 giờ liên tục',
        warranty: '12 Tháng Apple chính hãng tại Việt Nam',
      },
      description: 'Thiết kế nhôm nguyên khối sang trọng, hiệu năng chip M3 đột phá hỗ trợ AI NPU mạnh mẽ và khả năng xuất 2 màn hình rời cùng lúc.',
    },
    {
      id: 'prod-1',
      name: 'PC Gaming NEXUS TITAN X - RTX 4070 Ti Super 16GB',
      category: 'pc_gaming',
      brand: 'NEXUS',
      price: 36990000,
      originalPrice: 41500000,
      discountPercent: 11,
      inStock: true,
      stockCount: 8,
      rating: 4.9,
      reviewCount: 38,
      imageUrl: '',
      badge: 'Bán chạy nhất',
      installmentZero: true,
      giftPromotion: 'Tặng Tản nhiệt nước 360mm RGB + Gói bảo dưỡng 3 năm',
      isFeatured: true,
      specs: {
        cpu: 'Intel Core i7-14700F (20 nhân, 28 luồng, up to 5.4GHz)',
        mainboard: 'MSI B760M MORTAR WIFI DDR5',
        ram: '32GB (2x16GB) Corsair Vengeance RGB DDR5 6000MHz',
        gpu: 'NVIDIA GeForce RTX 4070 Ti Super 16GB GDDR6X',
        storage: '1TB SSD Kingston KC3000 PCIe 4.0 NVMe (7000MB/s)',
        psu: 'Deepcool PN750M 750W 80 Plus Gold ATX 3.0',
        cooling: 'Tản nhiệt nước AIO Deepcool LT720 360mm RGB',
        case: 'NZXT H6 Flow Dual Chamber Black Tempered Glass',
        warranty: '36 Tháng chính hãng 1 đổi 1',
      },
      description: 'Cỗ máy chiến game 2K/4K max settings và xử lý đồ họa render 3D, dựng phim Premiere/After Effects mượt mà. Được kỹ thuật viên cân chỉnh nhiệt độ và ép xung tối ưu.',
    },
    {
      id: 'prod-2',
      name: 'PC Đồ Họa & Render NEXUS STUDIO PRO - Ryzen 9 7900X',
      category: 'pc_gaming',
      brand: 'AMD',
      price: 42500000,
      originalPrice: 46900000,
      discountPercent: 9,
      inStock: true,
      stockCount: 5,
      rating: 5.0,
      reviewCount: 24,
      imageUrl: '',
      badge: 'Khuyên dùng cho Creator',
      installmentZero: true,
      giftPromotion: 'Tặng Windows 11 Pro bản quyền vĩnh viễn + Chuột không dây Logitech',
      isFeatured: true,
      specs: {
        cpu: 'AMD Ryzen 9 7900X (12 nhân, 24 luồng, up to 5.6GHz)',
        mainboard: 'ASUS TUF GAMING B650-PLUS WIFI',
        ram: '64GB (2x32GB) G.Skill Flare X5 DDR5 6000MHz',
        gpu: 'NVIDIA GeForce RTX 4080 Super 16GB Pro',
        storage: '2TB SSD Samsung 990 PRO Gen4 (7450MB/s)',
        psu: 'Corsair RM850e 850W 80 Plus Gold Modular',
        cooling: 'Thermalright Frozen Prism 360 White',
        case: 'Lian Li O11 Dynamic EVO White',
        warranty: '36 Tháng chính hãng',
      },
      description: 'Chuyên dụng cho kiến trúc sư, đồ họa 3D Blender, Unreal Engine 5 và AI model training với 64GB RAM DDR5 và GPU RTX 4080 Super đỉnh cao.',
    },
    {
      id: 'prod-3',
      name: 'Laptop ASUS ROG Zephyrus G16 (2025) OLED 240Hz',
      category: 'laptop',
      brand: 'ASUS',
      price: 48990000,
      originalPrice: 53900000,
      discountPercent: 9,
      inStock: true,
      stockCount: 4,
      rating: 4.8,
      reviewCount: 19,
      imageUrl: '',
      badge: 'Cao cấp siêu mỏng',
      installmentZero: true,
      giftPromotion: 'Tặng Balo ROG Slash + Chuột ROG Strix Impact III',
      isFeatured: true,
      specs: {
        cpu: 'Intel Core Ultra 9 185H (16 nhân, 22 luồng, NPU AI)',
        screen: '16 inch 2.5K (2560x1600) ROG Nebula OLED 240Hz 0.2ms',
        ram: '32GB LPDDR5X 7467MHz Onboard',
        storage: '1TB M.2 NVMe PCIe 4.0 SSD',
        gpu: 'NVIDIA GeForce RTX 4070 8GB GDDR6 (105W TGP)',
        weight: '1.85 kg khung nhôm CNC cao cấp',
        battery: '90Wh, sạc nhanh Type-C 100W PD',
        warranty: '24 Tháng chính hãng toàn cầu',
      },
      description: 'Tuyệt tác laptop gaming doanh nhân mỏng nhẹ chỉ 1.49cm, màn hình OLED 240Hz chuẩn màu 100% DCI-P3 cho đồ họa đỉnh cao.',
    },
    {
      id: 'prod-4',
      name: 'Laptop Lenovo Legion 5 Pro 16IRX9 - Core i7-14650HX',
      category: 'laptop',
      brand: 'Lenovo',
      price: 33490000,
      originalPrice: 36990000,
      discountPercent: 9,
      inStock: true,
      stockCount: 12,
      rating: 4.9,
      reviewCount: 52,
      imageUrl: '',
      badge: 'Quốc dân phân khúc',
      installmentZero: true,
      giftPromotion: 'Tặng Balo Lenovo Legion Gaming + Gói bảo hành tận nhà 24T',
      isFeatured: false,
      specs: {
        cpu: 'Intel Core i7-14650HX (16 nhân, 24 luồng, up to 5.2GHz)',
        screen: '16 inch WQXGA (2560x1600) IPS 165Hz 100% sRGB 500 nits',
        ram: '16GB DDR5 5600MHz (nâng cấp tối đa 64GB)',
        storage: '512GB SSD M.2 PCIe 4.0 NVMe',
        gpu: 'NVIDIA GeForce RTX 4060 8GB GDDR6 (140W max TGP)',
        cooling: 'Hệ thống tản nhiệt Legion Coldfront 5.0 buồng hơi',
        warranty: '24 Tháng Lenovo Premium Care tận nơi',
      },
      description: 'Dòng máy gaming được tin cậy nhất hiện nay với bàn phím TrueStrike gõ sướng, tản nhiệt buồng hơi mát lạnh và màn hình độ sáng 500 nits.',
    },
    {
      id: 'prod-5',
      name: 'Card Màn Hình ASUS TUF Gaming GeForce RTX 4070 Super 12GB',
      category: 'component',
      brand: 'ASUS',
      price: 18890000,
      originalPrice: 20990000,
      discountPercent: 10,
      inStock: true,
      stockCount: 15,
      rating: 4.9,
      reviewCount: 41,
      imageUrl: '',
      badge: 'Chính hãng',
      installmentZero: true,
      giftPromotion: 'Tặng Gá đỡ VGA chống xệ + Dây nguồn bọc lưới',
      isFeatured: false,
      specs: {
        gpu: 'NVIDIA GeForce RTX 4070 Super',
        vram: '12GB GDDR6X 192-bit',
        cuda: '7168 CUDA Cores',
        cooling: '3 quạt công nghệ Axial-tech với vòng bi kép',
        powerConnectors: '1x 16-pin 12VHPWR (nguồn tối thiểu 750W)',
        warranty: '36 Tháng chính hãng ASUS Việt Nam',
      },
      description: 'Linh kiện nâng cấp hoàn hảo giúp chơi mượt mà mọi tựa game AAA ở độ phân giải 2K Ray Tracing và DLSS 3 Frame Generation.',
    },
    {
      id: 'prod-6',
      name: 'Ổ Cứng SSD Samsung 990 PRO 1TB PCIe 4.0 NVMe M.2',
      category: 'component',
      brand: 'Samsung',
      price: 2790000,
      originalPrice: 3350000,
      discountPercent: 17,
      inStock: true,
      stockCount: 28,
      rating: 5.0,
      reviewCount: 88,
      imageUrl: '',
      badge: 'Tốc độ vô địch',
      installmentZero: false,
      giftPromotion: 'Miễn phí chuyển dữ liệu & cài đặt Windows',
      isFeatured: false,
      specs: {
        readSpeed: 'Đọc tuần tự lên tới 7450 MB/s',
        writeSpeed: 'Ghi tuần tự lên tới 6900 MB/s',
        controller: 'Bộ điều khiển Samsung Pascal độc quyền',
        dram: '1GB LPDDR4 Cache',
        tbw: '600 TBW độ bền cao',
        warranty: '60 Tháng chính hãng',
      },
      description: 'Ổ cứng SSD nhanh nhất chuẩn PCIe Gen4, hỗ trợ DirectStorage cho thời gian tải game và khởi động ứng dụng chỉ trong tích tắc.',
    },
    {
      id: 'prod-7',
      name: 'Bàn Phím Cơ Không Dây ASUS ROG Azoth 75% Custom OLED',
      category: 'accessory',
      brand: 'ASUS',
      price: 5490000,
      originalPrice: 6200000,
      discountPercent: 11,
      inStock: true,
      stockCount: 9,
      rating: 4.9,
      reviewCount: 31,
      imageUrl: '',
      badge: 'Custom cao cấp',
      installmentZero: true,
      giftPromotion: 'Tặng Bộ dụng cụ Lube Switch ROG chính hãng',
      isFeatured: false,
      specs: {
        layout: '75% nhỏ gọn (81 phím)',
        switch: 'ROG NX Snow Switch mượt mà (Hotswap thay thế dễ dàng)',
        display: 'Màn hình OLED 2 inch tích hợp núm xoay đa năng',
        connectivity: 'Bluetooth 5.1, Wireless 2.4GHz SpeedNova, Type-C',
        battery: 'Lên tới 2000 giờ sử dụng',
        warranty: '24 Tháng chính hãng',
      },
      description: 'Bàn phím cơ flagship với cấu trúc đệm Gasket mount 3 lớp tiêu âm, lube sẵn từ nhà máy, gõ êm ái và có màn hình OLED tùy biến ảnh GIF.',
    },
    {
      id: 'prod-8',
      name: 'Chuột Gaming Siêu Nhẹ Logitech G Pro X Superlight 2',
      category: 'accessory',
      brand: 'Logitech',
      price: 3290000,
      originalPrice: 3890000,
      discountPercent: 15,
      inStock: true,
      stockCount: 20,
      rating: 5.0,
      reviewCount: 94,
      imageUrl: '',
      badge: 'Top 1 Esports',
      installmentZero: false,
      giftPromotion: 'Tặng Bộ dán Grip Tape chống trượt cao cấp',
      isFeatured: false,
      specs: {
        weight: 'Chỉ 60 gram siêu nhẹ',
        sensor: 'Cảm biến HERO 2 độ phân giải 32.000 DPI, 500+ IPS',
        switch: 'Switch quang học cơ học Lightforce lai siêu bền',
        pollingRate: 'Tần số phản hồi 4000Hz không độ trễ',
        battery: 'Pin sạc lên tới 95 giờ',
        warranty: '24 Tháng chính hãng 1 đổi 1',
      },
      description: 'Vũ khí thi đấu được các tuyển thủ chuyên nghiệp CS2 và Valorant toàn cầu lựa chọn hàng đầu.',
    },
  ],
  services: [
    {
      id: 'srv-1',
      name: 'Sửa Chữa Phần Cứng Laptop / PC Lấy Liền',
      category: 'repair',
      priceEstimate: 'Từ 250.000₫ - 850.000₫',
      rawPrice: 250000,
      turnaroundTime: '30 - 90 Phút (Quan sát trực tiếp)',
      warrantyMonths: 6,
      iconName: 'Wrench',
      isPopular: true,
      description: 'Chẩn đoán và khắc phục dứt điểm các lỗi: máy không lên nguồn, mất sóng wifi, chập IC nguồn, lỗi bản lề gãy vỡ, thay bàn phím, sửa loa rè và màn hình sọc.',
      highlights: [
        'Quan sát trực tiếp toàn bộ quy trình kỹ thuật sửa chữa',
        'Ký tên lên từng linh kiện (Mainboard, Ổ cứng, RAM, Màn hình)',
        'Báo giá minh bạch trước khi làm, không phát sinh chi phí',
        'Bảo hành đổi mới linh kiện thay thế từ 6 - 12 tháng',
      ],
    },
    {
      id: 'srv-2',
      name: 'Vệ Sinh & Tra Keo Tản Nhiệt Cao Cấp (Thermal Grizzly)',
      category: 'maintenance',
      priceEstimate: '150.000₫ (PC) / 200.000₫ (Laptop)',
      rawPrice: 150000,
      turnaroundTime: '30 - 45 Phút',
      warrantyMonths: 3,
      iconName: 'ThermometerSnowflake',
      isPopular: true,
      description: 'Bảo dưỡng toàn diện: thổi bụi tĩnh điện, làm sạch cánh quạt, tra dầu bôi trơn trục quạt, thay thế keo tản nhiệt gốm Thermal Grizzly Kryonaut / Arctic MX-4 và thay thermal pad dẫn nhiệt.',
      highlights: [
        'Hạ nhiệt độ CPU & GPU ngay lập tức từ 15°C - 25°C',
        'Chống giật lag, tụt xung (thermal throttling) khi chơi game',
        'Kéo dài tuổi thọ chip xử lý và bảng mạch bo mạch chủ',
        'Tặng kèm quét virus và dọn dẹp rác hệ điều hành',
      ],
    },
    {
      id: 'srv-3',
      name: 'Cài Đặt Hệ Điều Hành & Phần Mềm Bản Quyền',
      category: 'software',
      priceEstimate: '150.000₫ - 250.000₫',
      rawPrice: 150000,
      turnaroundTime: '30 - 60 Phút',
      warrantyMonths: 1,
      iconName: 'Cpu',
      isPopular: false,
      description: 'Cài đặt Windows 11 Pro / Windows 10 sạch nguyên gốc, macOS mới nhất, cài trọn bộ driver chính hãng tối ưu, Office 365, phần mềm đồ họa Adobe Photoshop, AutoCAD, Premiere.',
      highlights: [
        'Bản cài Windows chuẩn Microsoft, không cài app rác hay tool ngầm',
        'Tối ưu hóa Registry giúp máy khởi động nhanh dưới 10 giây',
        'Cài đặt ứng dụng văn phòng, gõ tiếng Việt Unikey, giải nén WinRAR',
        'Sao lưu an toàn toàn bộ dữ liệu ổ C Desktop và Documents trước khi cài',
      ],
    },
    {
      id: 'srv-4',
      name: 'Cứu Dữ Liệu Ổ Cứng HDD / SSD / Thẻ Nhớ Chuyên Sâu',
      category: 'repair',
      priceEstimate: 'Từ 500.000₫ (tùy tình trạng)',
      rawPrice: 500000,
      turnaroundTime: '2 - 24 Giờ',
      warrantyMonths: 0,
      iconName: 'HardDrive',
      isPopular: false,
      description: 'Khôi phục dữ liệu bị xóa nhầm, format, ổ cứng bị bad sector, cháy bo mạch, kêu lạch cạch cơ học bằng thiết bị phòng sạch chuyên dụng MRT Lab & PC-3000.',
      highlights: [
        'Cam kết bảo mật tuyệt đối 100% dữ liệu đời tư và tài liệu doanh nghiệp',
        'Chỉ thanh toán phí khi cứu được đúng dữ liệu khách hàng cần',
        'Hỗ trợ trích xuất dữ liệu ra USB hoặc ổ cứng di động mang về',
      ],
    },
    {
      id: 'srv-5',
      name: 'Nâng Cấp Phần Cứng (SSD M.2 NVMe & RAM Lấy Liền)',
      category: 'upgrade',
      priceEstimate: 'Miễn phí công lắp ráp khi mua linh kiện',
      rawPrice: 100000,
      turnaroundTime: '15 - 30 Phút',
      warrantyMonths: 36,
      iconName: 'Zap',
      isPopular: true,
      description: 'Nâng cấp dung lượng RAM và thay thế ổ cứng cơ HDD bằng SSD NVMe tốc độ cao. Nhân bản (clone) toàn bộ dữ liệu và hệ điều hành cũ sang ổ mới không cần cài lại máy.',
      highlights: [
        'Máy tính cũ chạy chậm như rùa sẽ hồi sinh tốc độ nhanh gấp 10 lần',
        'Linh kiện SSD, RAM chính hãng Kingston, Crucial, Samsung, Corsair',
        'Miễn phí chuyển toàn bộ dữ liệu, ứng dụng và cài đặt cá nhân',
        'Bảo hành chính hãng 1 đổi 1 trong 36 tháng',
      ],
    },
    {
      id: 'srv-6',
      name: 'Tư Vấn & Lắp Ráp Dàn Máy PC Theo Ngân Sách',
      category: 'custom_build',
      priceEstimate: 'Miễn phí 100% công lắp đặt & đi dây',
      rawPrice: 0,
      turnaroundTime: '2 - 3 Giờ',
      warrantyMonths: 36,
      iconName: 'MonitorCheck',
      isPopular: false,
      description: 'Tư vấn cấu hình chuẩn xác theo nhu cầu: Gaming esport, Live stream, Kiến trúc Revit, Dựng video 4K hoặc chạy giả lập Nox/LDPlayer với mức chi phí tối ưu nhất.',
      highlights: [
        'Đi dây nguồn giấu dây chuyên nghiệp, thẩm mỹ tối đa luồng gió lưu thông',
        'Stress test kiểm tra độ ổn định FurMark & Cinebench trước khi giao',
        'Tặng gói vệ sinh và bảo dưỡng trọn đời máy tại cửa hàng',
        'Hỗ trợ giao hàng và lắp đặt tận nhà tại TP.HCM trong 2 giờ',
      ],
    },
  ],
  orders: [
    {
      id: 'ord-101',
      orderCode: 'NEX-8821',
      createdAt: '2026-09-23T14:30:00Z',
      customerName: 'Trần Văn Hoàng',
      customerPhone: '0912345678',
      customerAddress: '45 Lê Hồng Phong, P.4, Quận 5, TP.HCM',
      customerEmail: 'hoang.tran@gmail.com',
      type: 'product_order',
      totalAmount: 36990000,
      paymentMethod: 'vietqr',
      paymentStatus: 'paid',
      status: 'processing',
      items: [
        {
          productId: 'prod-1',
          name: 'PC Gaming NEXUS TITAN X - RTX 4070 Ti Super 16GB',
          price: 36990000,
          quantity: 1,
          imageUrl: '',
          specsSnippet: 'Core i7-14700F / RTX 4070 Ti Super / 32GB DDR5 / 1TB NVMe',
        },
      ],
      technicianNotes: 'Đã hoàn tất lắp ráp và cài Win 11 Pro + bộ game thử nghiệm. Đang chạy test nhiệt độ FurMark 30 phút.',
      trackingTimeline: [
        {
          time: '14:30 23/09',
          title: 'Đơn hàng được khởi tạo',
          note: 'Khách hàng thanh toán thành công qua chuyển khoản VietQR',
          completed: true,
        },
        {
          time: '15:10 23/09',
          title: 'Chuẩn bị linh kiện & Lắp ráp',
          note: 'Kỹ thuật viên Nguyễn Hùng đã xuất kho và tiến hành đi dây gọn gàng',
          completed: true,
        },
        {
          time: '17:00 23/09',
          title: 'Kiểm thử tải nặng (Stress test)',
          note: 'Nhiệt độ CPU 68°C, GPU 64°C - Đạt tiêu chuẩn xuất xưởng hoàn hảo',
          completed: true,
        },
        {
          time: 'Dự kiến 09:00 24/09',
          title: 'Giao hàng tận nơi',
          note: 'Bàn giao và hướng dẫn khách hàng nghiệm thu tại nhà',
          completed: false,
        },
      ],
    },
    {
      id: 'ord-102',
      orderCode: 'FIX-4402',
      createdAt: '2026-09-23T10:15:00Z',
      customerName: 'Lê Thị Thu Thảo',
      customerPhone: '0988776655',
      customerAddress: 'Căn hộ 12.04 Sunrise City, Quận 7, TP.HCM',
      customerEmail: 'thuthao.le@outlook.com',
      type: 'repair_appointment',
      totalAmount: 450000,
      paymentMethod: 'in_store',
      paymentStatus: 'unpaid',
      status: 'repairing',
      repairDetails: {
        serviceId: 'srv-2',
        serviceName: 'Vệ Sinh & Tra Keo Tản Nhiệt Cao Cấp + Cài Lại Win',
        deviceType: 'Laptop ASUS TUF Gaming F15 (2022)',
        issueDescription: 'Máy dùng bị nóng ran 95°C, quạt gió kêu to rít giật lag khi mở Photoshop, thỉnh thoảng sập nguồn đột ngột.',
        serviceLocation: 'at_shop',
        appointmentDate: '2026-09-24',
        appointmentTime: '10:00',
      },
      technicianNotes: 'Keo tản nhiệt cũ đã khô cứng hoàn toàn, đóng bụi dày đặc tại khe tản nhiệt. Đang tra keo Thermal Grizzly và làm sạch cụm tản đồng.',
      trackingTimeline: [
        {
          time: '10:15 23/09',
          title: 'Tiếp nhận thiết bị tại quầy',
          note: 'Kỹ thuật viên lập phiếu kiểm tra tình trạng máy cùng khách hàng',
          completed: true,
        },
        {
          time: '10:45 23/09',
          title: 'Tháo máy & Kiểm tra chi tiết',
          note: 'Quạt bám bụi nhiều, pad tản nhiệt cần thay mới. Báo giá khách đồng ý 450.000₫',
          completed: true,
        },
        {
          time: 'Đang xử lý',
          title: 'Vệ sinh siêu âm & Tra keo tản nhiệt',
          note: 'Tiến hành bôi keo gốm Kryonaut và tra dầu vòng bi quạt',
          completed: true,
        },
        {
          time: 'Dự kiến 11:30 24/09',
          title: 'Sẵn sàng giao trả máy',
          note: 'Quý khách có thể tới cửa hàng nhận máy và kiểm tra thực tế',
          completed: false,
        },
      ],
    },
    {
      id: 'ord-103',
      orderCode: 'NEX-7719',
      createdAt: '2026-09-22T09:00:00Z',
      customerName: 'Nguyễn Quốc Bảo',
      customerPhone: '0903332211',
      customerAddress: '88 Nguyễn Đình Chiểu, Quận 3, TP.HCM',
      type: 'product_order',
      totalAmount: 2790000,
      paymentMethod: 'cod',
      paymentStatus: 'paid',
      status: 'completed',
      items: [
        {
          productId: 'prod-6',
          name: 'Ổ Cứng SSD Samsung 990 PRO 1TB PCIe 4.0 NVMe M.2',
          price: 2790000,
          quantity: 1,
          imageUrl: '',
          specsSnippet: 'Tốc độ 7450MB/s / Bảo hành 60T',
        },
      ],
      technicianNotes: 'Đã giao thành công cho khách, khách nhận hàng hài lòng và đánh giá 5 sao.',
      trackingTimeline: [
        {
          time: '09:00 22/09',
          title: 'Đơn hàng hoàn tất',
          note: 'Đã thu tiền COD và bàn giao phiếu bảo hành chính hãng',
          completed: true,
        },
      ],
    },
  ],
  customers: [
    {
      id: 'cust-1',
      name: 'Trần Văn Hoàng',
      phone: '0912345678',
      email: 'hoang.tran@gmail.com',
      address: '45 Lê Hồng Phong, P.4, Quận 5, TP.HCM',
      totalSpent: 36990000,
      orderCount: 1,
      registeredAt: '2026-09-23',
      rank: 'VIP Vàng',
      notes: 'Khách hàng thân thiết, làm trong ngành dựng phim quảng cáo.',
    },
    {
      id: 'cust-2',
      name: 'Lê Thị Thu Thảo',
      phone: '0988776655',
      email: 'thuthao.le@outlook.com',
      address: 'Căn hộ 12.04 Sunrise City, Quận 7, TP.HCM',
      totalSpent: 450000,
      orderCount: 1,
      registeredAt: '2026-09-23',
      rank: 'Thành viên',
      notes: 'Hay đem laptop gaming đến vệ sinh định kỳ mỗi 6 tháng.',
    },
    {
      id: 'cust-3',
      name: 'Nguyễn Quốc Bảo',
      phone: '0903332211',
      email: 'baonq@techcorp.vn',
      address: '88 Nguyễn Đình Chiểu, Quận 3, TP.HCM',
      totalSpent: 12590000,
      orderCount: 4,
      registeredAt: '2026-08-10',
      rank: 'VIP Bạc',
      notes: 'Thường mua linh kiện nâng cấp cho dàn máy văn phòng công ty.',
    },
  ],
  banners: [
    {
      id: 'banner-1',
      badge: 'ĐẠI HỘI CÔNG NGHỆ 2026',
      badgeColor: 'bg-sky-500',
      title: 'Back To School: Giảm Tới 50% Laptop & PC',
      subtitle: 'Tặng thêm màn hình 24 inch hoặc Balo Gaming cao cấp trị giá 1.500.000₫ cho học sinh, sinh viên.',
      ctaText: 'Săn Deal Ngay',
      ctaAction: 'flash_sale',
      bgGradientDark: 'from-slate-900 via-sky-950/60 to-slate-950',
      bgGradientLight: 'from-sky-100 via-white to-sky-50',
      accentColor: 'text-sky-500',
      isActive: true,
    },
    {
      id: 'banner-2',
      badge: 'DÀN PC GAMING ĐỈNH CAO',
      badgeColor: 'bg-sky-600',
      title: 'PC Gaming RTX 4070 Ti Super - Giảm 4.500.000₫',
      subtitle: 'Tặng trọn bộ tản nhiệt nước AIO 360mm RGB + Chuột Esports không dây + Bảo hành 1 đổi 1 tận nơi.',
      ctaText: 'Xem Cấu Hình',
      ctaAction: 'category',
      targetCategory: 'pc_gaming',
      bgGradientDark: 'from-slate-900 via-cyan-950/50 to-slate-950',
      bgGradientLight: 'from-cyan-100 via-white to-sky-50',
      accentColor: 'text-cyan-500',
      isActive: true,
    },
    {
      id: 'banner-3',
      badge: 'DỊCH VỤ SỬA CHỮA ỦY QUYỀN',
      badgeColor: 'bg-sky-500',
      title: 'Sửa Chữa Laptop Lấy Liền 30 Phút - Ký Tên Linh Kiện',
      subtitle: 'Miễn phí kiểm tra lỗi phần cứng, vệ sinh tra keo tản nhiệt Thermal Grizzly và bảo dưỡng trọn đời.',
      ctaText: 'Đặt Lịch Tiếp Nhận',
      ctaAction: 'booking',
      bgGradientDark: 'from-slate-900 via-sky-950/40 to-slate-950',
      bgGradientLight: 'from-sky-50 via-white to-cyan-50',
      accentColor: 'text-sky-500',
      isActive: true,
    },
  ],
  branches: [
    {
      id: 'st-sole',
      name: 'Trần Hoa Computer - Cửa Hàng & Phòng Lab Duy Nhất',
      city: 'thainguyen',
      cityName: 'Thái Nguyên',
      address: 'Phú Thịnh - Thái Nguyên (Cơ sở duy nhất, không có chi nhánh toàn quốc)',
      hotline: '0963284044',
      hours: '08:00 - 21:30 (Mở cửa tất cả các ngày trong tuần & ngày lễ)',
      features: ['Cửa hàng duy nhất trên toàn quốc', 'Phòng lab sửa máy lấy liền 30P', 'Hỗ trợ kỹ thuật qua Zalo 0963284044', 'Ship COD kiểm tra hàng tận nơi'],
      isMain: true,
    },
  ],
  pcBuildPackages: [
    {
      id: 'build-esport',
      name: 'PC Gaming ESPORT HERO - i3 12100F / RX 6600 8GB',
      price: 12490000,
      originalPrice: 14200000,
      target: 'Chiến mượt mà CS2, Valorant, Liên Minh Huyền Thoại, FIFA Online 4 trên 180 FPS.',
      specs: {
        cpu: 'Intel Core i3-12100F (4 nhân, 8 luồng)',
        mainboard: 'ASUS PRIME H610M-K D4',
        ram: '16GB (2x8GB) Kingston Fury Beast DDR4 3200MHz',
        gpu: 'ASRock AMD Radeon RX 6600 Challenger 8GB',
        storage: '512GB SSD Kingston NV2 PCIe 4.0 NVMe',
        psu: 'Aigo VK550 550W',
        case: 'Xigmatek NYX 3F Black (3 quạt RGB)',
        cooling: 'Tản nhiệt khí Jonsbo CR-1000 EVO RGB',
      },
    },
    {
      id: 'build-2k',
      name: 'PC Gaming E-POWER BATTLESHIP - i5 13400F / RTX 4060 8GB',
      price: 18990000,
      originalPrice: 22500000,
      target: 'Cân mượt mà Black Myth Wukong, Cyberpunk 2077, GTA V, đồ họa Premiere Pro 2K.',
      specs: {
        cpu: 'Intel Core i5-13400F (10 nhân, 16 luồng)',
        mainboard: 'Gigabyte B760M GAMING PLUS D4',
        ram: '16GB (2x8GB) Corsair Vengeance Pro RGB 3200MHz',
        gpu: 'MSI GeForce RTX 4060 VENTUS 2X 8GB OC',
        storage: '512GB SSD M.2 PCIe Gen4 NVMe (3500MB/s)',
        psu: 'Cooler Master Elite V4 600W 80 Plus',
        case: 'Xigmatek Aqua M Black 3 Fan RGB',
        cooling: 'Tản nhiệt khí Thermalright Assassin X 120 Refined SE',
      },
    },
    {
      id: 'build-streamer',
      name: 'PC Creator & Streamer TITAN - Ryzen 7 7700X / RTX 4070 Super',
      price: 32900000,
      originalPrice: 36500000,
      target: 'Chuyên dụng live stream đa nền tảng, render 3D kiến trúc, chơi game 2K/4K max settings.',
      specs: {
        cpu: 'AMD Ryzen 7 7700X (8 nhân, 16 luồng, 5.4GHz)',
        mainboard: 'MSI B650M GAMING PLUS WIFI DDR5',
        ram: '32GB (2x16GB) G.Skill Ripjaws S5 DDR5 6000MHz',
        gpu: 'ASUS Dual GeForce RTX 4070 Super 12GB GDDR6X',
        storage: '1TB SSD Kingston KC3000 Gen4 (7000MB/s)',
        psu: 'Deepcool PN750M 750W 80 Plus Gold Modular',
        case: 'NZXT H5 Flow Black',
        cooling: 'Tản nhiệt nước AIO Deepcool LT520 240mm RGB',
      },
    },
    {
      id: 'build-flagship',
      name: 'PC GODLIKE ULTRA - i7 14700F / RTX 4080 Super 16GB / 64GB RAM',
      price: 49990000,
      originalPrice: 54900000,
      target: 'Cỗ máy tối thượng cho huấn luyện mô hình AI, thiết kế Maya/Houdini và game 4K Ray Tracing đỉnh cao.',
      specs: {
        cpu: 'Intel Core i7-14700F (20 nhân, 28 luồng, up to 5.4GHz)',
        mainboard: 'ASUS ROG STRIX B760-F GAMING WIFI',
        ram: '64GB (2x32GB) Corsair Dominator Platinum DDR5 6000MHz',
        gpu: 'GIGABYTE GeForce RTX 4080 Super WINDFORCE V2 16GB',
        storage: '2TB SSD Samsung 990 PRO Gen4 (7450MB/s)',
        psu: 'Corsair RM850e 850W 80 Plus Gold ATX 3.0',
        case: 'Lian Li O11 Dynamic EVO RGB Black',
        cooling: 'Tản nhiệt nước AIO ASUS ROG RYUJIN III 360 ARGB',
      },
    },
  ],
  websiteContent: {
    showAnnouncement: true,
    announcementText: '🔥 ĐẠI TIỆC CÔNG NGHỆ: Giảm đến 50% Laptop & PC · Thu cũ đổi mới trợ giá 5 triệu · Vệ sinh & tra keo tản nhiệt miễn phí · Trả góp 0%',
    flashSaleActive: true,
    flashSaleTitle: 'GIỜ VÀNG GIÁ SỐC - SĂN DEAL CHỚP NHOÁNG',
    flashSaleSubtitle: 'Số lượng có hạn, áp dụng cho các đơn hàng hoàn tất thanh toán hôm nay',
    flashSaleHours: 3,
    catalogBadge: 'CHÍNH HÃNG 100% · BẢO HÀNH TẬN TÂM',
    catalogTitle: 'Laptop, PC Gaming & Linh Kiện Tuyển Chọn',
    catalogSubtitle: 'Tất cả sản phẩm đều được kiểm tra nhiệt độ kỹ lưỡng, cài sẵn Windows bản quyền và bảo hành 1 đổi 1 tận nơi.',
    servicesBadge: 'TRUNG TÂM KỸ THUẬT TIÊU CHUẨN CAO',
    servicesTitle: 'Dịch Vụ Sửa Chữa & Bảo Dưỡng Máy Tính Lấy Liền',
    servicesSubtitle: 'Khách hàng quan sát trực tiếp kỹ thuật viên thao tác trong 30-60 phút. Ký tên lên từng linh kiện, cam kết không tráo đổi đồ.',
    showroomsBadge: 'CƠ SỞ DUY NHẤT TẠI PHÚ THỊNH - THÁI NGUYÊN',
    showroomsTitle: 'Cửa Hàng & Phòng Lab Kỹ Thuật Duy Nhất',
    showroomsSubtitle: 'Cửa hàng không có bất cứ chi nhánh nào trên toàn quốc. Quý khách liên hệ hotline 0963284044, Zalo zalo.me/84963284044 hoặc ghé trực tiếp Phú Thịnh - Thái Nguyên.',
    trustPledges: [
      {
        id: 'pledge-1',
        title: '100% Minh Bạch',
        description: 'Báo giá trước khi sửa chữa. Khách hàng ký nhận bo mạch và linh kiện.',
        iconType: 'shield',
      },
      {
        id: 'pledge-2',
        title: 'Lấy Liền 30-60 Phút',
        description: 'Xử lý sự cố phần cứng, thay màn hình, vệ sinh máy ngay tại phòng lab mở.',
        iconType: 'clock',
      },
      {
        id: 'pledge-3',
        title: 'Trả Góp 0% Lãi Suất',
        description: 'Hỗ trợ trả góp qua thẻ tín dụng và CCCD gắn chip chỉ 5 phút duyệt.',
        iconType: 'card',
      },
      {
        id: 'pledge-4',
        title: '1 Đổi 1 Trong 30 Ngày',
        description: 'Lỗi phần cứng do nhà sản xuất được đổi máy mới ngay lập tức.',
        iconType: 'award',
      },
    ],
    footerDescription: 'Cửa hàng TRẦN HOA COMPUTER chỉ có duy nhất 01 địa chỉ tại Phú Thịnh - Thái Nguyên và không có bất cứ chi nhánh nào trên toàn quốc. Hotline tư vấn: 0963284044 · Email: hotrokhachhang@tranhoacomputer.site · Zalo hỗ trợ: zalo.me/84963284044',
    footerCopyright: 'Bản quyền © 2026 TRẦN HOA COMPUTER. Địa chỉ duy nhất: Phú Thịnh - Thái Nguyên. Đã thông báo Bộ Công Thương · DMCA Protected',
    sectionVisibility: {
      showMarquee: true,
      showHeroSlider: true,
      showShowroomsStrip: true,
      showFlashSale: true,
      showCatalog: true,
      showPCBuilder: true,
      showServices: true,
      showTechArticles: true,
      showShowroomsMap: true,
      showTrustPledges: true,
    },
    vouchers: [
      {
        id: 'vouch-1',
        code: 'CHAOMUNG2026',
        discountType: 'fixed',
        discountValue: 300000,
        minOrderValue: 5000000,
        usageLimit: 500,
        usedCount: 142,
        expiresAt: '2026-12-31',
        active: true,
      },
      {
        id: 'vouch-2',
        code: 'VIPTECH500',
        discountType: 'fixed',
        discountValue: 500000,
        minOrderValue: 15000000,
        usageLimit: 200,
        usedCount: 88,
        expiresAt: '2026-12-31',
        active: true,
      },
      {
        id: 'vouch-3',
        code: 'THAINGUYEN100',
        discountType: 'fixed',
        discountValue: 100000,
        minOrderValue: 1000000,
        usageLimit: 1000,
        usedCount: 315,
        expiresAt: '2026-12-31',
        active: true,
      },
    ],
    taxNumber: '0201988291',
    businessLicense: 'Đăng ký kinh doanh tại Phú Thịnh - Thái Nguyên',
    bctCertificateNumber: 'Đã Thông Báo Bộ Công Thương (Quyết định số 9482/TB-BCT)',
    complaintHotline: '0963284044 (Trần Hoa Computer CSKH)',
    facebookFanpage: 'https://facebook.com/tranhoacomputer',
    tiktokShop: 'https://tiktok.com/@tranhoacomputer',
    youtubeChannel: 'https://youtube.com/@tranhoacomputer',
  },
  users: [
    {
      id: 'user-demo-1',
      name: 'Nguyễn Văn An',
      phone: '0912345678',
      email: 'nguyenvanan.tech@gmail.com',
      address: 'Số 152 Đường Lạch Tray, Quận Ngô Quyền, Hải Phòng',
      city: 'Hải Phòng',
      district: 'Quận Ngô Quyền',
      avatarUrl: '',
      provider: 'google',
      rank: 'VIP Vàng',
      totalSpent: 28500000,
      orderCount: 3,
      createdAt: '2026-01-15T08:00:00Z',
    },
  ],
  currentUser: null,
};
