import { ActivityItem, MetricCardData } from './types';

export const mockActivities: ActivityItem[] = [
  {
    id: 'act-1',
    name: 'design-system-core',
    category: 'Kho mã nguồn',
    status: 'Hoạt động',
    dateModified: 'Hôm nay lúc 10:45',
    iconType: 'folder',
  },
  {
    id: 'act-2',
    name: 'tai_lieu_ky_thuat_v2.md',
    category: 'Tài liệu',
    status: 'Chờ duyệt',
    dateModified: 'Hôm qua lúc 16:12',
    iconType: 'file',
  },
  {
    id: 'act-3',
    name: 'tien-trinh-phan-tich-du-lieu',
    category: 'Tích hợp',
    status: 'Hoạt động',
    dateModified: '20 Th09, 2026',
    iconType: 'layers',
  },
  {
    id: 'act-4',
    name: 'dich-vu-xac-thuc-nguoi-dung',
    category: 'Kho mã nguồn',
    status: 'Hoạt động',
    dateModified: '19 Th09, 2026',
    iconType: 'folder',
  },
  {
    id: 'act-5',
    name: 'ban-ve-giao-dien-mobile.fig',
    category: 'Thiết kế',
    status: 'Chờ duyệt',
    dateModified: '18 Th09, 2026',
    iconType: 'file',
  },
  {
    id: 'act-6',
    name: 'cong-thanh-toan-webhook',
    category: 'Tích hợp',
    status: 'Hoạt động',
    dateModified: '17 Th09, 2026',
    iconType: 'layers',
  },
  {
    id: 'act-7',
    name: 'cau-truc-co-so-du-lieu.sql',
    category: 'Cấu hình',
    status: 'Đang xử lý',
    dateModified: '16 Th09, 2026',
    iconType: 'file',
  },
  {
    id: 'act-8',
    name: 'dich-vu-gui-thong-bao',
    category: 'Kho mã nguồn',
    status: 'Hoạt động',
    dateModified: '15 Th09, 2026',
    iconType: 'folder',
  },
  {
    id: 'act-9',
    name: 'cau-hinh-ha-tang-terraform',
    category: 'Cấu hình',
    status: 'Hoạt động',
    dateModified: '14 Th09, 2026',
    iconType: 'layers',
  },
  {
    id: 'act-10',
    name: 'bao-cao-kiem-toan-bao-mat.pdf',
    category: 'Tài liệu',
    status: 'Chờ duyệt',
    dateModified: '12 Th09, 2026',
    iconType: 'file',
  },
  {
    id: 'act-11',
    name: 'cong-thong-tin-khach-hang',
    category: 'Kho mã nguồn',
    status: 'Đã lưu trữ',
    dateModified: '10 Th09, 2026',
    iconType: 'folder',
  },
  {
    id: 'act-12',
    name: 'quy-tac-xoa-cache-cdn',
    category: 'Cấu hình',
    status: 'Hoạt động',
    dateModified: '08 Th09, 2026',
    iconType: 'layers',
  },
];

export const mockMetrics: MetricCardData[] = [
  {
    id: 'metric-card-1',
    title: 'Tổng số dự án',
    value: '24',
    iconName: 'FolderGit2',
    iconColor: 'text-indigo-600',
    changeText: '+3 dự án trong tháng này',
    changeColor: 'text-emerald-600',
    progressPercent: 75,
    progressStatus: 'Tiến độ hoàn thành: 18/24 dự án',
    progressColor: 'bg-indigo-600',
    trackColor: 'bg-indigo-50',
  },
  {
    id: 'metric-card-2',
    title: 'Công việc đang chạy',
    value: '58',
    iconName: 'Clock',
    iconColor: 'text-amber-500',
    changeText: '8 việc đến hạn trong 48h',
    changeColor: 'text-slate-500',
    progressPercent: 62,
    progressStatus: 'Đã giải quyết: 36/58 công việc',
    progressColor: 'bg-amber-500',
    trackColor: 'bg-amber-50',
  },
  {
    id: 'metric-card-3',
    title: 'Thành viên nhóm',
    value: '16',
    iconName: 'Users',
    iconColor: 'text-blue-500',
    changeText: '100% vị trí đang hoạt động',
    changeColor: 'text-emerald-600',
    progressPercent: 88,
    progressStatus: 'Phân bổ nhân sự: 14/16 dự án',
    progressColor: 'bg-blue-600',
    trackColor: 'bg-blue-50',
  },
  {
    id: 'metric-card-4',
    title: 'Trạng thái hệ thống',
    value: '99.98%',
    iconName: 'CheckCircle2',
    iconColor: 'text-emerald-500',
    changeText: 'Hoạt động ổn định trên mọi máy chủ',
    changeColor: 'text-slate-500',
    progressPercent: 96,
    progressStatus: 'Đạt 96% cam kết chất lượng SLA',
    progressColor: 'bg-emerald-600',
    trackColor: 'bg-emerald-50',
  },
];
